(function () {
const BOARD_SIZE = 13;

const STONE = {
  black: "black",
  white: "white",
};

const problems = [
  {
    id: "사활-두집만들기-1778949030771",
    title: "두집만들기",
    description: "두집만들기",
    level: "30급",
    category: "사활",
    stones: [
      { x: 0, y: 10, color: STONE.white },
      { x: 1, y: 10, color: STONE.white },
      { x: 2, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.white },
      { x: 4, y: 10, color: STONE.white },
      { x: 0, y: 11, color: STONE.black },
      { x: 1, y: 11, color: STONE.black },
      { x: 2, y: 11, color: STONE.black },
      { x: 3, y: 11, color: STONE.black },
      { x: 4, y: 11, color: STONE.white },
      { x: 3, y: 12, color: STONE.black },
      { x: 4, y: 12, color: STONE.white },
    ],
    correctMove: { x: 1, y: 12 },
  },
  {
    id: "uploaded-capture-20260516-01",
    title: "따내기 문제 1",
    description: "상대 돌을 잡는 정답 1수를 찾아보세요.",
    level: "",
    category: "따내기",
    stones: [
      { x: 5, y: 8, color: STONE.white },
      { x: 1, y: 9, color: STONE.white },
      { x: 3, y: 9, color: STONE.white },
      { x: 5, y: 9, color: STONE.white },
      { x: 1, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.white },
      { x: 4, y: 10, color: STONE.black, mark: "triangle" },
      { x: 5, y: 10, color: STONE.white },
      { x: 6, y: 10, color: STONE.black },
      { x: 0, y: 11, color: STONE.black },
      { x: 1, y: 11, color: STONE.black },
      { x: 2, y: 11, color: STONE.black },
      { x: 3, y: 11, color: STONE.black },
      { x: 4, y: 11, color: STONE.white, mark: "triangle" },
      { x: 5, y: 11, color: STONE.black },
      { x: 7, y: 11, color: STONE.black },
      { x: 1, y: 12, color: STONE.white },
      { x: 4, y: 12, color: STONE.white, mark: "triangle" },
      { x: 5, y: 12, color: STONE.black },
    ],
    correctMove: { x: 6, y: 11 },
  },
  {
    id: "uploaded-capture-20260516-02",
    title: "따내기 문제 2",
    description: "상대 돌을 잡는 정답 1수를 찾아보세요.",
    level: "",
    category: "따내기",
    stones: [
      { x: 3, y: 7, color: STONE.white },
      { x: 4, y: 7, color: STONE.white },
      { x: 5, y: 7, color: STONE.white },
      { x: 1, y: 8, color: STONE.white },
      { x: 2, y: 8, color: STONE.white },
      { x: 3, y: 8, color: STONE.black, mark: "triangle" },
      { x: 4, y: 8, color: STONE.black, mark: "triangle" },
      { x: 5, y: 8, color: STONE.black, mark: "triangle" },
      { x: 6, y: 8, color: STONE.white },
      { x: 1, y: 9, color: STONE.white },
      { x: 2, y: 9, color: STONE.black, mark: "triangle" },
      { x: 3, y: 9, color: STONE.white, mark: "triangle" },
      { x: 5, y: 9, color: STONE.white },
      { x: 6, y: 9, color: STONE.black },
      { x: 1, y: 10, color: STONE.black },
      { x: 3, y: 10, color: STONE.black },
      { x: 6, y: 10, color: STONE.black },
    ],
    correctMove: { x: 4, y: 9 },
  },
  {
    id: "uploaded-ladder-20260516-01",
    title: "축 문제 1",
    description: "축의 흐름을 읽고 정답 1수를 찾아보세요.",
    level: "",
    category: "축",
    stones: [
      { x: 2, y: 6, color: STONE.white },
      { x: 2, y: 7, color: STONE.white },
      { x: 3, y: 7, color: STONE.black },
      { x: 4, y: 7, color: STONE.black },
      { x: 5, y: 7, color: STONE.white },
      { x: 6, y: 7, color: STONE.white },
      { x: 2, y: 8, color: STONE.white },
      { x: 3, y: 8, color: STONE.black },
      { x: 4, y: 8, color: STONE.white, mark: "triangle" },
      { x: 5, y: 8, color: STONE.black },
      { x: 6, y: 8, color: STONE.black },
      { x: 1, y: 9, color: STONE.black },
      { x: 2, y: 9, color: STONE.black },
      { x: 3, y: 9, color: STONE.white, mark: "triangle" },
      { x: 4, y: 9, color: STONE.white, mark: "triangle" },
      { x: 2, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.black },
    ],
    correctMove: { x: 5, y: 9 },
  },
  {
    id: "uploaded-life-death-20260516-01",
    title: "사활 문제 1",
    description: "흑이 살거나 백을 잡는 정답 1수를 찾아보세요.",
    level: "",
    category: "사활",
    stones: [
      { x: 4, y: 8, color: STONE.white },
      { x: 5, y: 8, color: STONE.white },
      { x: 2, y: 9, color: STONE.white },
      { x: 3, y: 9, color: STONE.white },
      { x: 4, y: 9, color: STONE.black },
      { x: 5, y: 9, color: STONE.black },
      { x: 6, y: 9, color: STONE.white },
      { x: 7, y: 9, color: STONE.white },
      { x: 2, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.black },
      { x: 6, y: 10, color: STONE.black },
      { x: 7, y: 10, color: STONE.white },
      { x: 2, y: 11, color: STONE.white },
      { x: 3, y: 11, color: STONE.black },
      { x: 4, y: 11, color: STONE.black },
      { x: 6, y: 11, color: STONE.black },
      { x: 7, y: 11, color: STONE.white },
      { x: 3, y: 12, color: STONE.white },
      { x: 5, y: 12, color: STONE.black },
      { x: 7, y: 12, color: STONE.white },
    ],
    correctMove: { x: 5, y: 10 },
  },
  {
    id: "uploaded-life-death-20260516-02",
    title: "사활 문제 2",
    description: "흑이 살거나 백을 잡는 정답 1수를 찾아보세요.",
    level: "",
    category: "사활",
    stones: [
      { x: 2, y: 6, color: STONE.black },
      { x: 0, y: 7, color: STONE.black },
      { x: 1, y: 7, color: STONE.black },
      { x: 1, y: 8, color: STONE.white },
      { x: 2, y: 8, color: STONE.black },
      { x: 3, y: 8, color: STONE.black },
      { x: 0, y: 9, color: STONE.white },
      { x: 2, y: 9, color: STONE.white },
      { x: 3, y: 9, color: STONE.black },
      { x: 1, y: 10, color: STONE.white },
      { x: 2, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.black },
      { x: 1, y: 11, color: STONE.white },
      { x: 2, y: 11, color: STONE.black },
      { x: 3, y: 11, color: STONE.black },
      { x: 0, y: 12, color: STONE.white },
    ],
    correctMove: { x: 1, y: 9 },
  },
  {
    id: "단수-백을-잡아보세요-1778924439683",
    title: "백을 잡아보세요",
    description: "문제 설명을 입력하세요.",
    level: "30급",
    category: "따내기",
    stones: [
      { x: 1, y: 8, color: STONE.white },
      { x: 2, y: 8, color: STONE.black },
      { x: 3, y: 8, color: STONE.black },
      { x: 1, y: 9, color: STONE.white },
      { x: 2, y: 9, color: STONE.black },
      { x: 3, y: 9, color: STONE.black },
      { x: 4, y: 9, color: STONE.black },
      { x: 2, y: 10, color: STONE.white },
      { x: 3, y: 10, color: STONE.white },
      { x: 4, y: 10, color: STONE.black },
      { x: 1, y: 11, color: STONE.white },
      { x: 2, y: 11, color: STONE.black },
      { x: 3, y: 11, color: STONE.black },
      { x: 4, y: 11, color: STONE.white },
      { x: 5, y: 11, color: STONE.white },
    ],
    correctMove: { x: 1, y: 10 },
  },
  {
    id: "uploaded-connect-black-01",
    title: "흑을 연결해 보세요",
    description: "흑돌을 연결하는 수를 찾아보세요.",
    level: "30급",
    category: "활로",
    stones: [
      { x: 5, y: 6, color: STONE.black },
      { x: 4, y: 7, color: STONE.black },
      { x: 6, y: 7, color: STONE.black },
      { x: 3, y: 6, color: STONE.white },
      { x: 4, y: 6, color: STONE.white },
      { x: 2, y: 7, color: STONE.white },
      { x: 5, y: 8, color: STONE.white },
    ],
    correctMove: { x: 5, y: 7 },
  },
  {
    id: "uploaded-connect-black-02",
    title: "흑을 연결해 보세요",
    description: "흑돌이 끊기지 않도록 연결해보세요.",
    level: "30급",
    category: "활로",
    stones: [
      { x: 2, y: 5, color: STONE.black },
      { x: 3, y: 5, color: STONE.black },
      { x: 4, y: 6, color: STONE.black },
      { x: 3, y: 7, color: STONE.black },
      { x: 5, y: 7, color: STONE.black },
      { x: 4, y: 5, color: STONE.white },
      { x: 5, y: 5, color: STONE.white },
      { x: 2, y: 6, color: STONE.white },
      { x: 2, y: 7, color: STONE.white },
      { x: 2, y: 8, color: STONE.white },
      { x: 4, y: 10, color: STONE.white },
    ],
    correctMove: { x: 4, y: 7 },
  },
  {
    id: "uploaded-cut-white-01",
    title: "백을 끊어보시오",
    description: "백돌의 연결을 끊는 수를 찾아보세요.",
    level: "30급",
    category: "따내기",
    stones: [
      { x: 2, y: 7, color: STONE.black },
      { x: 3, y: 7, color: STONE.black },
      { x: 4, y: 7, color: STONE.black },
      { x: 2, y: 8, color: STONE.black },
      { x: 6, y: 8, color: STONE.black },
      { x: 7, y: 8, color: STONE.black },
      { x: 5, y: 6, color: STONE.white },
      { x: 5, y: 7, color: STONE.white },
      { x: 3, y: 8, color: STONE.white },
      { x: 4, y: 8, color: STONE.white },
    ],
    correctMove: { x: 5, y: 8 },
  },
  {
    id: "capture-race-01",
    title: "끊는 수 찾기",
    description:
      "상대의 연결을 끊어 흑이 주도권을 잡는 한 수를 찾아보세요. 정답은 흑 1수입니다.",
    level: "15급",
    category: "따내기",
    stones: [
      { x: 5, y: 5, color: STONE.black },
      { x: 6, y: 6, color: STONE.black },
      { x: 7, y: 5, color: STONE.black },
      { x: 5, y: 6, color: STONE.white },
      { x: 6, y: 4, color: STONE.white },
      { x: 7, y: 6, color: STONE.white },
    ],
    correctMove: { x: 6, y: 5 },
  },
  {
    id: "life-and-death-01",
    title: "급소로 사는 수",
    description:
      "백돌에게 둘러싸인 흑돌이 두 눈을 만들 수 있는 급소를 찾아보세요.",
    level: "12급",
    category: "사활",
    stones: [
      { x: 2, y: 2, color: STONE.black },
      { x: 3, y: 2, color: STONE.black },
      { x: 4, y: 2, color: STONE.black },
      { x: 2, y: 3, color: STONE.black },
      { x: 4, y: 3, color: STONE.black },
      { x: 2, y: 4, color: STONE.black },
      { x: 3, y: 4, color: STONE.black },
      { x: 4, y: 4, color: STONE.black },
      { x: 1, y: 2, color: STONE.white },
      { x: 2, y: 1, color: STONE.white },
      { x: 4, y: 1, color: STONE.white },
      { x: 5, y: 2, color: STONE.white },
      { x: 5, y: 4, color: STONE.white },
      { x: 4, y: 5, color: STONE.white },
      { x: 2, y: 5, color: STONE.white },
      { x: 1, y: 4, color: STONE.white },
    ],
    correctMove: { x: 3, y: 3 },
  },
  {
    id: "tesuji-01",
    title: "축을 피하는 행마",
    description:
      "상대의 추격을 피하면서 형태를 안정시키는 흑의 좋은 행마를 찾아보세요.",
    level: "10급",
    category: "축",
    stones: [
      { x: 6, y: 7, color: STONE.black },
      { x: 7, y: 8, color: STONE.black },
      { x: 8, y: 8, color: STONE.black },
      { x: 6, y: 6, color: STONE.white },
      { x: 7, y: 7, color: STONE.white },
      { x: 9, y: 8, color: STONE.white },
      { x: 8, y: 9, color: STONE.white },
    ],
    correctMove: { x: 8, y: 7 },
  },
];

window.BadukProblems = {
  BOARD_SIZE,
  STONE,
  problems,
};
})();
