export const appState = {
  mode: "list",
  selectedLevelGroup: "입문",
  selectedCategory: "전체",
  currentProblemIndex: 0,
  solvedAnswerKeys: new Set(),
  isSolved: false,
  isAiThinking: false,
  pendingAiTimeout: null,
  autoNextTimeout: null,
  wrongModalTimeout: null,
  wrongResetTimeout: null,
  canDismissAnswerModal: false,
  selectedPrintProblemIds: new Set(),
  playedMoves: [],
  initialBoardStones: [],
  reviewSession: null,
  pendingCategoryCompletion: null,
  studyExpandedLevelGroups: null,
};
